### PR TITLE
fix: update .net sdk to newer LTS, correct typos

### PR DESCRIPTION
**Pull request by mrneo240**
copy of PR #46

### CODE REVIEW

**Comment by sonik-br** [comment]
Hi!
Take a look at the `openMenu` branch. It's already updated to dot net 6.
It's the most recent version and it will replace the old one. I'm just out of time to run more tests on this version.

**Comment by mrneo240** [comment]
The file GDMENUCardManager.AvaloniaUI.csproj
Shows netcoreapp3.1 currently

**Comment by sonik-br** [comment]
Oh! Sorry about that. My mistake.
I have a local commit pending a push.
I'm going to push a new update in a day or two. Also doing a change that megavolt asked for.

**Comment by sonik-br** [comment]
@mrneo240 I've got all my changes merged into master branch.
Want to rebase and do a new pr?
I can also accept the pr minus the two src code changes as they are not needed anymore.

**Pull request merged**
